### ISSUE TITLE
DatePicker duplication bug

### ISSUE THREAD

**Issue by nathan-moore-techsur** [MetroStar/comet#186]
**Describe the bug**
The DatePicker initializes every time the parent component renders, which adds partially visible calendar icon buttons.

**To Reproduce**
Create this component and add it to a comet-starter page (typing in input adds more icons):

```JavaScript
function MyComponent() {
  const [myInput, setMyInput] = useState('');

  console.log(myInput);

  return (
    <div>
      <TextInput
        id="my-input"
        onChange={(e) => setMyInput(e.target.value)}
      ></TextInput>
      <DatePicker></DatePicker>
    </div>
  );
}
```

**Expected behavior**
The DatePicker is initialized once instead of on every component rerender.

**Screenshots**
Top edges of multiple calendar buttons:
![datepicker_bug](https://github.com/MetroStar/comet/assets/97469321/4d060b13-8d39-48ad-81e9-d191637a6386)

Multiple `usa-date-picker__wrapper` divs:
![dom](https://github.com/MetroStar/comet/assets/97469321/d3b319f6-9442-496f-94f0-09626b67d999)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser Chromium
 - Version 126.0.6478.126

**Smartphone (please complete the following information):**
- (Not tested on smartphone)

**Additional context**
- The re-initializing on every render might be due to the `useLayoutEffect` not having any dependencies: https://github.com/MetroStar/comet/blob/338d5deff555e3bca7c5ccdb018f15ea5850b817/packages/comet-uswds/src/components/date-picker/date-picker.tsx#L68
- If a dependency list is added, though, it still renders twice from `<React.StrictMode>`.

**Comment by jbouder** [comment]
Thanks @nathan-moore-techsur , i'll review today and will get back to you as soon as I have some updates.

**Comment by jbouder** [comment]
This should now be resolved. In addition to adding an dependency array, I also had to do a little bit of a check to make sure it only calls the uswds `on` function once.

My testing checks out, can you verify?

**Comment by jbouder** [comment]
Glad to hear it.
