### ISSUE TITLE
Sorting indicator support for the Table component when binding with custom data

### ISSUE THREAD

**Issue by nk922** [MetroStar/comet#219]
**Is your feature request related to a problem? Please describe.**
Not related to an issue; request for enhancement

**Describe the solution you'd like**
Would be great to have the table show sort indicator (column/direction) when binding with the custom data.  Would also like to have an event raised from the component when user changes the column for sorting or changes the sort direction (from ascending to descending and vice versa).  Component should also accept the sort column and direction for the initial render.  After the initial render the sort column and direction would be managed from the header row within the Table component.  Only some of the columns would be sortable and at a time only one column would be sortable.  This is for situations where the filtering and sorting of the data is done at the micro-services layer to make sure UI only binds to the data that it needs and no more.

**Describe alternatives you've considered**
No alternatives considered.  If there are viable alternatives to achieve similar functionality that adheres to USWDS guidelines please recommend.

**Additional context**
none

**Comment by jbouder** [comment]
Is this in reference to the comet-uswds Table or the comet-extras DataTable? And can you provide an example of what your custom data looks like?

**Comment by nk922** [comment]
comet-uswds

 const cols = React.useMemo(
    () => [
      {
        id: 'name',
        name: 'Name',
      },
      {
        id: 'status',
        name: 'Status',
      },
      {
        id: 'created',
        name: 'Date Created',
      },
      {
        id: 'updated',
        name: 'Date Updated',
      },
    ],
    [],
  );

**Comment by jbouder** [comment]
A couple of thoughts...
1. I believe you should be able to get a table to sort with any kind of data type, as long as you set the sortValue appropriately, like example here: https://metrostar.github.io/comet/?path=/docs/uswds-table--docs.
2. I can confirm the table does not provide any kind of `onSort` type functionality, that would be a good addition though. I'll put that on my list, but sure when I'll get to it
3. You should be able to set the initial sort using the `sortDir` and `sortIndex` props
4. The more advanced dynamic toggling of sorting of columns might be doable
5. Have you tried using the DataTable? Its basically a skinned implementation of the Tanstack Datatable, which should be completely customizable.

Lastly, just wanted to note that you are always welcome to fork the repo and create a PR for any changes you would like to add.

**Comment by jbouder** [comment]
@nk922 , I went ahead and spent a little time trying to get some updates ready to support your table needs. A new beta release has been created as follows: `@metrostar/comet-uswds@2.4.0-beta.2`. See the PR linked above for details and please let me know if this covers everything.

**Comment by jbouder** [comment]
FYI, `2.4.0` was published with the above enhancements.

**Comment by nk922** [comment]
As soon as I added sortable={true} on the Table the data binding stopped working:

![image](https://github.com/user-attachments/assets/2be9b008-a621-47d0-a086-c9861d112b11)

this is how the table looked like before the adding the sotrable={true}:

![image](https://github.com/user-attachments/assets/c7b920ee-57fe-4c60-8ed0-239416791565)

Also, what should my onSort method/event handler look like to capture the new sort column and the sort direction?

**Comment by jbouder** [comment]
> As soon as I added sortable={true} on the Table the data binding stopped working:
> 
> ![image](https://private-user-images.githubusercontent.com/145782116/355951185-2be9b008-a621-47d0-a086-c9861d112b11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNTkzNTIsIm5iZiI6MTcyMzA1OTA1MiwicGF0aCI6Ii8xNDU3ODIxMTYvMzU1OTUxMTg1LTJiZTliMDA4LWE2MjEtNDdkMC1hMDg2LWM5ODYxZDExMmIxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxOTMwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDFkYzI3MjMzNzQ4MmYxYTIzZTljYmU3ODRkNjA2OGZhZThlNDcwZjZkYmY5ZWNjYjkxMzJjY2YwZDk2YTI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6jkZ2PNB-PdK_YTLsmX91xEAJeo-RtbXr53Ron6k_oc)
> 
> this is how the table looked like before the adding the sotrable={true}:
> 
> ![image](https://private-user-images.githubusercontent.com/145782116/355952061-c7b920ee-57fe-4c60-8ed0-239416791565.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNTkzNTIsIm5iZiI6MTcyMzA1OTA1MiwicGF0aCI6Ii8xNDU3ODIxMTYvMzU1OTUyMDYxLWM3YjkyMGVlLTU3ZmUtNGM2MC04ZWQwLTIzOTQxNjc5MTU2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxOTMwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Y2IzMDcxOTRhZDcxODYyNzg1ZThkNDY1NzNhODc3NDI3M2JmNmZmY2M1ZGFjNmMzYzJmMWMwNTVjMTg1NTlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3LIJ09thl7K0deVV2a1mWvvaZV2qZl1HDreeQmuRmCY)
> 
> Also, what should my onSort method/event handler look like to capture the new sort column and the sort direction?

I’m not sure you’re applying the sortable in the right place. Please take a look at the story here for a working example: https://github.com/MetroStar/comet/blob/365a255d47856b69a711d65bcdf2403ea15344dc/packages/comet-uswds/src/components/table/table.stories.tsx#L16

Also, you can pass any function into the onSort prop. Here is a story showing a basic example: https://github.com/MetroStar/comet/blob/365a255d47856b69a711d65bcdf2403ea15344dc/packages/comet-uswds/src/components/table/table.stories.tsx#L117

**Comment by nk922** [comment]
Also, looks like the arrow direction and the tooltip for ascending/descending indicator is inverse of what's expected for the initial render

**Comment by jbouder** [comment]
> Also, looks like the arrow direction and the tooltip for ascending/descending indicator is inverse of what's expected for the initial render

This looks to be a new issue, I added as a bug here to track the fix: https://github.com/MetroStar/comet/issues/229

**Comment by nk922** [comment]
may be there is a disconnect in how I need this functionality vs how it's enhanced in its current form.  I need to be able to get from the Table the new sort direction and the indicator when user clicks on those arrows; I don't need the grid to do its own sorting.  Also, I need to be doing my own sorting from a microservice when that occurs.

For my table the filtering, paging, and sorting is implemented in a microservice and I'll not be relying on the sorting by the Table.  I hope I have tried to explain the disconnect well/stated my expectations.

**Comment by jbouder** [comment]
> may be there is a disconnect in how I need this functionality vs how it's enhanced in its current form. I need to be able to get from the Table the new sort direction and the indicator when user clicks on those arrows; I don't need the grid to do its own sorting. Also, I need to be doing my own sorting from a microservice when that occurs.
> 
> For my table the filtering, paging, and sorting is implemented in a microservice and I'll not be relying on the sorting by the Table. I hope I have tried to explain the disconnect well/stated my expectations.

I see. I’m going to suggest that what you’re trying to do might be a bit too specific for this more generalized implementation of the USWDS Table. A few suggestions I might have:
1. Make use of the Comet Extras DataTable, as it provides much more flexibility and functionality.
2. If you think this functionality would fit the USWDS Table, feel free to open a PR with the enhancements.
3. Create your own local version of the Table in your project, and enhance as needed. All of the code for this implementation can be found in the repo.

**Comment by jbouder** [comment]
> > Also, looks like the arrow direction and the tooltip for ascending/descending indicator is inverse of what's expected for the initial render
> 
> This looks to be a new issue, I added as a bug here to track the fix: #229

@nk922 , I have a fix in for the table sorting reverse order issue. Can you test this beta release? `@metrostar/comet-uswds@2.4.1-beta.0`

**Comment by jbouder** [comment]
> I created a new fork from https://github.com/MetroStar/comet at https://github.com/nk922/comet. How can I make refer to this locally to test my changes?

You could either create a project in NPM and publish there or you could keep it local. I assume you want to keep it all local, which isn't something I'm super familiar with. This article however seems to provide some good instructions: https://medium.com/@oresoftware/node-js-how-to-test-your-new-npm-module-without-publishing-it-every-5-minutes-3b6f8e0491dd
